name: Asana integration for GitHub PRs
on:
  workflow_dispatch:
  pull_request:
    types: [review_requested, closed, opened, reopened, converted_to_draft, edited, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/asana.yml@main
    with:
      development-section: "In Development"
      review-section: "Pending Review"
      merged-section: "Merged / Not Deployed"
      trigger-phrase: "\\*\\*Asana Ticket:\\*\\*"
      attach-pr: true
    secrets:
      asana-token: ${{ secrets.ASANA_PERSONAL_ACCESS_TOKEN }}
      github-secret: ${{ secrets.ASANA_GITHUB_INTEGRATION_SECRET }}
