name: Deploy to Prod

on:
  workflow_dispatch:
  release:
    types:
      - released

permissions:
  contents: read # Needed to checkout repo

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  check-ref:
    name: Fail if not a tag
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Failing intentionally. Only tags may be deployed to prod."
          exit 1
  checkout:
    name: Check out code
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
  call-workflow:
    name: Call MBTA deploy-ecs workflow
    needs: checkout
    permissions:
      contents: read # Needed to checkout repo
      id-token: write # Needed to access ECR and ECS
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@c76e5ccd9556fbea52bc41548f7ceed5985ad775 # v5.1.0
    with:
      app-name: api
      environment: ${{ inputs.environment }}
      docker-additional-tags: ${{ inputs.environment }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
