name: Deploy to lower environment (dev etc)

on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: dev
        required: true
  push:
    branches: master

permissions:
  contents: read # Needed to checkout repo

concurrency:
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  check-env:
    name: Fail if production environment
    if: ${{ inputs.environment == 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Failing intentionally. Please use the 'Deploy to production' workflow."
          exit 1
  call-workflow:
    name: Call MBTA deploy-ecs workflow
    if: ${{ inputs.environment != 'prod' }}
    permissions:
      contents: read # Needed to checkout repo
      id-token: write # Needed to access ECR and ECS
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@c76e5ccd9556fbea52bc41548f7ceed5985ad775 # v5.1.0
    with:
      app-name: api
      environment: ${{ inputs.environment }}
      docker-additional-tags: ${{ inputs.environment }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
