name: Deploy to Prod

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod
    concurrency: prod
    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v2
      - name: Get commit metadata
        run: |
          echo SHA_SHORT=$(git rev-parse --short ${{ github.sha }}) >> $GITHUB_ENV
      - name: Deploy to EB
        uses: mbta/beanstalk-deploy@v17
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: api
          environment_name: api-dev-green
          version_label: ${{ env.SHA_SHORT }}
          region: ${{ env.AWS_REGION }}
      # - uses: mbta/actions/notify-slack-deploy@v1
      #   if: ${{ !cancelled() }}
      #   with:
      #     webhook-url: ${{ secrets.SLACK_WEBHOOK }}
      #     job-status: ${{ job.status }}
